version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shortener_db
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener
      POSTGRES_DB: shortener
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local